USE [master]
GO

/****** Object:  Database [db_a6dce2_pincma]    Script Date: 19/10/2022 16:06:10 ******/
CREATE DATABASE [db_a6dce2_pincma]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db_a6dce2_pincma_Data', FILENAME = N'H:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\db_a6dce2_pincma_DATA.mdf' , SIZE = 8192KB , MAXSIZE = 512000KB , FILEGROWTH = 10%)
 LOG ON 
( NAME = N'db_a6dce2_pincma_Log', FILENAME = N'H:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\db_a6dce2_pincma_Log.LDF' , SIZE = 3072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db_a6dce2_pincma].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [db_a6dce2_pincma] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [db_a6dce2_pincma] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [db_a6dce2_pincma] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [db_a6dce2_pincma] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [db_a6dce2_pincma] SET ARITHABORT OFF 
GO

ALTER DATABASE [db_a6dce2_pincma] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [db_a6dce2_pincma] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [db_a6dce2_pincma] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [db_a6dce2_pincma] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [db_a6dce2_pincma] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [db_a6dce2_pincma] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [db_a6dce2_pincma] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [db_a6dce2_pincma] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [db_a6dce2_pincma] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [db_a6dce2_pincma] SET  ENABLE_BROKER 
GO

ALTER DATABASE [db_a6dce2_pincma] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [db_a6dce2_pincma] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [db_a6dce2_pincma] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [db_a6dce2_pincma] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [db_a6dce2_pincma] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [db_a6dce2_pincma] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [db_a6dce2_pincma] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [db_a6dce2_pincma] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [db_a6dce2_pincma] SET  MULTI_USER 
GO

ALTER DATABASE [db_a6dce2_pincma] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [db_a6dce2_pincma] SET DB_CHAINING OFF 
GO

ALTER DATABASE [db_a6dce2_pincma] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [db_a6dce2_pincma] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [db_a6dce2_pincma] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [db_a6dce2_pincma] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [db_a6dce2_pincma] SET QUERY_STORE = OFF
GO

ALTER DATABASE [db_a6dce2_pincma] SET  READ_WRITE 
GO


